"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Download, CheckCircle, AlertCircle, ArrowLeft, Loader2 } from "lucide-react";
import Link from "next/link";

export default function EvaluationSummaryPage() {
  const { id } = useParams() as { id: string };
  const [loading, setLoading] = useState(true);
  
  const [interview, setInterview] = useState<any>(null);
  const [summary, setSummary] = useState<any>(null);
  const [questions, setQuestions] = useState<any[]>([]);
  const [questionCount, setQuestionCount] = useState(0);
  const [exporting, setExporting] = useState(false);

  useEffect(() => {
    async function loadDataAndGenerateSummary() {
      const supabase = createClient();
      
      // 1. Fetch Interview Data
      const { data: interviewData, error: interviewError } = await supabase
        .from("interviews")
        .select("*")
        .eq("id", id)
        .single();
        
      if (interviewError || !interviewData) {
        console.error("Failed to load interview", interviewError);
        return;
      }
      setInterview(interviewData);

      // 2. Fetch Questions (for count and for PDF export)
      const { data: qData, error: qError } = await supabase
        .from("interview_questions")
        .select("*")
        .eq("interview_id", id)
        .order("order_index", { ascending: true });
        
      if (!qError && qData) {
        setQuestions(qData);
        setQuestionCount(qData.length);
      }

      // 3. Trigger / Fetch AI Summary
      try {
        const response = await fetch("/api/generate-summary", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ interviewId: id }),
        });
        const data = await response.json();
        
        if (data.success && data.summary) {
          setSummary(data.summary);
        } else {
          console.error("Summary Generation Error:", data);
        }
      } catch (err) {
        console.error("Failed to fetch summary API:", err);
      } finally {
        setLoading(false);
      }
    }

    loadDataAndGenerateSummary();
  }, [id]);

  function getRecommendationColor(rec: string | undefined) {
    if (rec === "Strong Hire" || rec === "Hire") return "bg-green-600 hover:bg-green-700";
    if (rec === "Maybe") return "bg-yellow-600 hover:bg-yellow-700";
    if (rec === "Reject") return "bg-red-600 hover:bg-red-700";
    return "bg-primary";
  }

  const handleExportPDF = async () => {
    setExporting(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF();
      const margin = 20;
      const pageWidth = doc.internal.pageSize.getWidth();
      const maxLineWidth = pageWidth - margin * 2;
      let y = 20;

      const checkPageBreak = (neededHeight = 10) => {
        if (y + neededHeight > 280) {
          doc.addPage();
          y = 20;
        }
      };

      // Header
      doc.setFont("helvetica", "bold");
      doc.setFontSize(22);
      doc.setTextColor(0, 0, 0);
      doc.text("Candidate Assessment Report", margin, y);
      y += 8;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text("Generated by VivaGen AI", margin, y);
      y += 15;

      // Candidate Info
      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.setTextColor(0, 0, 0);
      doc.text(interview.candidate_name, margin, y);
      y += 8;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(12);
      doc.setTextColor(60, 60, 60);
      doc.text(`Role: ${interview.role} (${interview.level})`, margin, y);
      y += 6;
      doc.text(`Primary Stack: ${interview.language}`, margin, y);
      y += 6;
      doc.text(`Date: ${new Date(interview.created_at).toLocaleDateString()}`, margin, y);
      y += 15;

      // Score Box Approximation
      doc.setFillColor(243, 244, 246);
      doc.roundedRect(margin, y, 70, 25, 3, 3, "F");
      
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text("Final Score", margin + 5, y + 8);
      
      doc.setFont("helvetica", "bold");
      doc.setFontSize(18);
      doc.setTextColor(17, 24, 39);
      doc.text(`${interview.percentage?.toFixed(1) || 0}%`, margin + 5, y + 15);
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text(`${interview.total_score} / ${interview.max_score} pts`, margin + 5, y + 21);
      
      y += 40;

      const printList = (title: string, items: string[]) => {
        if (!items || items.length === 0) return;
        checkPageBreak(20);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text(title, margin, y);
        y += 8;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);
        doc.setTextColor(40, 40, 40);

        items.forEach((item: string) => {
          const lines = doc.splitTextToSize(`• ${item}`, maxLineWidth - 5);
          checkPageBreak(lines.length * 6);
          doc.text(lines, margin + 2, y);
          y += lines.length * 5 + 2;
        });
        y += 10;
      };

      printList("Key Strengths", summary.strengths);
      printList("Areas for Growth", summary.weaknesses);

      // Questions
      checkPageBreak(25);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text("Interview Questions & Scores", margin, y);
      y += 10;

      questions.forEach((q: any, i: number) => {
        const qText = `${i + 1}. ${q.question}`;
        
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.setTextColor(17, 24, 39);
        
        const lines = doc.splitTextToSize(qText, maxLineWidth - 30); // leave room for score
        checkPageBreak(lines.length * 6 + 15);
        
        doc.text(lines, margin, y);
        
        // Output score on the same line as the first line of the question, right aligned
        const scoreString = `${q.score || 0}/10`;
        const scoreWidth = doc.getTextWidth(scoreString);
        doc.text(scoreString, pageWidth - margin - scoreWidth, y);
        
        y += lines.length * 5 + 2;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(`Type: ${q.type.charAt(0).toUpperCase() + q.type.slice(1)} | Difficulty: ${q.difficulty}/10`, margin, y);
        
        y += 12;
      });

      doc.save(`${interview.candidate_name.replace(/\s+/g, '_')}_Interview_Report.pdf`);

    } catch (error) {
      console.error("Export failed", error);
      alert("Failed to create PDF");
    } finally {
      setExporting(false);
    }
  };

  if (loading) {
    return (
      <div className="flex flex-col h-[calc(100vh-8rem)] items-center justify-center space-y-4">
        <Loader2 className="h-10 w-10 animate-spin text-primary" />
        <h2 className="text-xl font-semibold">Gemini AI is evaluating the interview...</h2>
        <p className="text-muted-foreground text-sm max-w-sm text-center">
          Analyzing scores and interviewer notes to generate strengths, weaknesses, and a final recommendation.
        </p>
      </div>
    );
  }

  if (!interview || !summary) {
    return (
      <div className="container mx-auto p-6 max-w-4xl text-center pt-20">
        <h2 className="text-2xl font-bold text-destructive mb-2">Evaluation Failed</h2>
        <p className="text-muted-foreground mb-6">We couldn't generate the summary at this time.</p>
        <Link href="/dashboard">
          <Button>Back to Dashboard</Button>
        </Link>
      </div>
    );
  }

  return (
    <div className="container mx-auto p-6 max-w-4xl space-y-8">
      <div className="flex justify-between items-center mb-8">
        <div>
          <Link href="/dashboard" className="text-sm text-muted-foreground flex items-center hover:text-primary mb-4 transition-colors">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Dashboard
          </Link>
          <h1 className="text-3xl font-bold tracking-tight">Interview Evaluation Summary</h1>
          <p className="text-muted-foreground mt-1">Generated by Google Gemini AI</p>
        </div>
        <Button size="lg" className="shadow-md" onClick={handleExportPDF} disabled={exporting}>
          {exporting ? (
            <Loader2 className="mr-2 h-5 w-5 animate-spin" />
          ) : (
            <Download className="mr-2 h-5 w-5" />
          )}
          {exporting ? "Generating PDF..." : "Download Shareable PDF"}
        </Button>
      </div>

      <div className="grid md:grid-cols-3 gap-6">
        <Card className="md:col-span-2">
          <CardHeader className="bg-muted/30 border-b">
            <div className="flex justify-between items-start">
              <div className="space-y-1">
                <CardTitle className="text-2xl">{interview.candidate_name}</CardTitle>
                <CardDescription className="text-base text-primary font-medium">{interview.role}</CardDescription>
              </div>
              <Badge variant="default" className={`text-lg py-1 px-3 ${getRecommendationColor(summary.recommendation)}`}>
                {summary.recommendation}
              </Badge>
            </div>
          </CardHeader>
          <CardContent className="pt-6 space-y-6">
            <div>
              <h3 className="text-lg font-semibold mb-2">AI Summary</h3>
              <p className="text-muted-foreground leading-relaxed whitespace-pre-wrap">
                {summary.summary || "No summary available."}
              </p>
            </div>

            <div className="grid sm:grid-cols-2 gap-6 pt-4 border-t">
              <div>
                <h3 className="text-lg font-semibold text-green-600 mb-4 flex items-center">
                  <CheckCircle className="mr-2 h-5 w-5" />
                  Key Strengths
                </h3>
                <ul className="space-y-3">
                  {summary.strengths?.length > 0 ? summary.strengths.map((str: string, i: number) => (
                    <li key={i} className="flex items-start">
                      <span className="mr-2 mt-1 block h-1.5 w-1.5 rounded-full bg-green-600 shrink-0"></span>
                      <span className="text-sm">{str}</span>
                    </li>
                  )) : (
                    <p className="text-sm text-muted-foreground">None identified.</p>
                  )}
                </ul>
              </div>

              <div>
                <h3 className="text-lg font-semibold text-amber-600 mb-4 flex items-center">
                  <AlertCircle className="mr-2 h-5 w-5" />
                  Areas for Growth
                </h3>
                <ul className="space-y-3">
                  {summary.weaknesses?.length > 0 ? summary.weaknesses.map((weak: string, i: number) => (
                    <li key={i} className="flex items-start">
                      <span className="mr-2 mt-1 block h-1.5 w-1.5 rounded-full bg-amber-600 shrink-0"></span>
                      <span className="text-sm">{weak}</span>
                    </li>
                  )) : (
                    <p className="text-sm text-muted-foreground">None identified.</p>
                  )}
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>

        <div className="space-y-6">
          <Card className="border-t-4 border-t-primary">
            <CardHeader className="pb-4">
              <CardTitle>Final Score</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-end gap-2 text-primary font-bold">
                <span className="text-5xl leading-none">{interview.percentage?.toFixed(1) || 0}</span>
                <span className="text-2xl text-muted-foreground pb-1">%</span>
              </div>
              <p className="text-sm text-muted-foreground mt-2 font-medium">
                Score: {interview.total_score} / {interview.max_score} total points
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="pb-4">
              <CardTitle className="text-base">Interview Details</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <div className="flex justify-between py-1 border-b">
                <span className="text-sm text-muted-foreground">Date</span>
                <span className="text-sm font-medium">
                  {new Date(interview.created_at).toLocaleDateString()}
                </span>
              </div>
              <div className="flex justify-between py-1 border-b">
                <span className="text-sm text-muted-foreground">Level</span>
                <span className="text-sm font-medium capitalize">{interview.level}</span>
              </div>
              <div className="flex justify-between py-1 border-b">
                <span className="text-sm text-muted-foreground">Questions</span>
                <span className="text-sm font-medium">{questionCount}</span>
              </div>
              <div className="flex justify-between py-1">
                <span className="text-sm text-muted-foreground">Primary Stack</span>
                <span className="text-sm font-medium">{interview.language}</span>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
