"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Download, CheckCircle, AlertCircle, ArrowLeft, Loader2, History } from "lucide-react";
import Link from "next/link";

export default function EvaluationSummaryPage() {
  const { id } = useParams() as { id: string };
  const [loading, setLoading] = useState(true);
  
  const [interview, setInterview] = useState<any>(null);
  const [summary, setSummary] = useState<any>(null);
  const [questions, setQuestions] = useState<any[]>([]);
  const [questionCount, setQuestionCount] = useState(0);
  const [exporting, setExporting] = useState(false);

  useEffect(() => {
    async function loadDataAndGenerateSummary() {
      const supabase = createClient();
      
      // 1. Fetch Interview Data
      const { data: interviewData, error: interviewError } = await supabase
        .from("interviews")
        .select("*")
        .eq("id", id)
        .single();
        
      if (interviewError || !interviewData) {
        console.error("Failed to load interview", interviewError);
        return;
      }
      setInterview(interviewData);

      // 2. Fetch Questions (for count and for PDF export)
      const { data: qData, error: qError } = await supabase
        .from("interview_questions")
        .select("*")
        .eq("interview_id", id)
        .order("order_index", { ascending: true });
        
      if (!qError && qData) {
        setQuestions(qData);
        setQuestionCount(qData.length);
      }

      // 3. Trigger / Fetch AI Summary
      try {
        const response = await fetch("/api/generate-summary", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ interviewId: id }),
        });
        const data = await response.json();
        
        if (data.success && data.summary) {
          setSummary(data.summary);
        } else {
          console.error("Summary Generation Error:", data);
        }
      } catch (err) {
        console.error("Failed to fetch summary API:", err);
      } finally {
        setLoading(false);
      }
    }

    loadDataAndGenerateSummary();
  }, [id]);

  function getRecommendationColor(rec: string | undefined) {
    if (rec === "Strong Hire" || rec === "Hire") return "bg-green-600 hover:bg-green-700";
    if (rec === "Maybe") return "bg-yellow-600 hover:bg-yellow-700";
    if (rec === "Reject") return "bg-red-600 hover:bg-red-700";
    return "bg-primary";
  }

  const handleExportPDF = async () => {
    setExporting(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF();
      const margin = 20;
      const pageWidth = doc.internal.pageSize.getWidth();
      const maxLineWidth = pageWidth - margin * 2;
      let y = 20;

      const checkPageBreak = (neededHeight = 10) => {
        if (y + neededHeight > 280) {
          doc.addPage();
          y = 20;
        }
      };

      // Header
      doc.setFont("helvetica", "bold");
      doc.setFontSize(22);
      doc.setTextColor(0, 0, 0);
      doc.text("Candidate Assessment Report", margin, y);
      y += 8;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text("Generated by VivaGen AI", margin, y);
      y += 15;

      // Candidate Info
      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.setTextColor(0, 0, 0);
      doc.text(interview.candidate_name, margin, y);
      y += 8;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(12);
      doc.setTextColor(60, 60, 60);
      doc.text(`Role: ${interview.role} (${interview.level})`, margin, y);
      y += 6;
      doc.text(`Primary Stack: ${interview.language}`, margin, y);
      y += 6;
      doc.text(`Date: ${new Date(interview.created_at).toLocaleDateString()}`, margin, y);
      y += 15;

      // Score Box Approximation
      doc.setFillColor(243, 244, 246);
      doc.roundedRect(margin, y, 70, 25, 3, 3, "F");
      
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text("Final Score", margin + 5, y + 8);
      
      doc.setFont("helvetica", "bold");
      doc.setFontSize(18);
      doc.setTextColor(17, 24, 39);
      doc.text(`${interview.percentage?.toFixed(1) || 0}%`, margin + 5, y + 15);
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text(`${interview.total_score} / ${interview.max_score} pts`, margin + 5, y + 21);
      
      y += 40;

      const printList = (title: string, items: string[]) => {
        if (!items || items.length === 0) return;
        checkPageBreak(20);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text(title, margin, y);
        y += 8;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);
        doc.setTextColor(40, 40, 40);

        items.forEach((item: string) => {
          const lines = doc.splitTextToSize(`• ${item}`, maxLineWidth - 5);
          checkPageBreak(lines.length * 6);
          doc.text(lines, margin + 2, y);
          y += lines.length * 5 + 2;
        });
        y += 10;
      };

      printList("Key Strengths", summary.strengths);
      printList("Areas for Growth", summary.weaknesses);

      // Questions
      checkPageBreak(25);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text("Interview Questions & Scores", margin, y);
      y += 10;

      questions.forEach((q: any, i: number) => {
        const qText = `${i + 1}. ${q.question}`;
        
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.setTextColor(17, 24, 39);
        
        const lines = doc.splitTextToSize(qText, maxLineWidth - 30); // leave room for score
        checkPageBreak(lines.length * 6 + 15);
        
        doc.text(lines, margin, y);
        
        // Output score on the same line as the first line of the question, right aligned
        const scoreString = `${q.score || 0}/10`;
        const scoreWidth = doc.getTextWidth(scoreString);
        doc.text(scoreString, pageWidth - margin - scoreWidth, y);
        
        y += lines.length * 5 + 2;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(`Type: ${q.type.charAt(0).toUpperCase() + q.type.slice(1)} | Difficulty: ${q.difficulty}/10`, margin, y);
        
        y += 12;
      });

      doc.save(`${interview.candidate_name.replace(/\s+/g, '_')}_Interview_Report.pdf`);

    } catch (error) {
      console.error("Export failed", error);
      alert("Failed to create PDF");
    } finally {
      setExporting(false);
    }
  };

  if (loading) {
    return (
      <div className="flex flex-col h-[calc(100vh-8rem)] items-center justify-center space-y-4">
        <Loader2 className="h-10 w-10 animate-spin text-primary" />
        <h2 className="text-xl font-semibold">Gemini AI is evaluating the interview...</h2>
        <p className="text-muted-foreground text-sm max-w-sm text-center">
          Analyzing scores and interviewer notes to generate strengths, weaknesses, and a final recommendation.
        </p>
      </div>
    );
  }

  if (!interview || !summary) {
    return (
      <div className="container mx-auto p-6 max-w-4xl text-center pt-20">
        <h2 className="text-2xl font-bold text-destructive mb-2">Evaluation Failed</h2>
        <p className="text-muted-foreground mb-6">We couldn't generate the summary at this time.</p>
        <Link href="/dashboard">
          <Button>Back to Dashboard</Button>
        </Link>
      </div>
    );
  }

  return (
    <div className="container mx-auto p-4 md:p-8 max-w-5xl space-y-10 animate-in fade-in duration-500">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
        <div>
          <Link href="/dashboard" className="text-xs font-bold text-muted-foreground uppercase tracking-widest flex items-center hover:text-primary mb-4 transition-colors group">
            <ArrowLeft className="mr-2 h-3 w-3 group-hover:-translate-x-1 transition-transform" />
            Back to Workspace
          </Link>
          <h1 className="text-4xl font-black tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-foreground to-foreground/60">
            Interview Report
          </h1>
          <p className="text-muted-foreground mt-2 font-medium">Evaluation generated by AI Intelligence</p>
        </div>
        <Button 
          size="lg" 
          className="w-full md:w-auto shadow-xl shadow-primary/20 rounded-full px-8 hover:scale-105 transition-transform" 
          onClick={handleExportPDF} 
          disabled={exporting}
        >
          {exporting ? (
            <Loader2 className="mr-2 h-5 w-5 animate-spin" />
          ) : (
            <Download className="mr-2 h-5 w-5" />
          )}
          {exporting ? "Finalizing PDF..." : "Export Assessment PDF"}
        </Button>
      </div>

      <div className="grid lg:grid-cols-3 gap-8">
        <Card className="lg:col-span-2 border-none shadow-2xl shadow-primary/5 rounded-3xl overflow-hidden ring-1 ring-primary/5">
          <CardHeader className="bg-muted/30 dark:bg-muted/10 border-b p-8">
            <div className="flex flex-col sm:flex-row justify-between items-start gap-4">
              <div className="space-y-1">
                <CardTitle className="text-3xl font-black">{interview.candidate_name}</CardTitle>
                <div className="flex items-center gap-2">
                  <Badge variant="secondary" className="bg-primary text-primary-foreground font-bold">{interview.role}</Badge>
                  <Badge variant="outline" className="font-bold border-muted-foreground/30 capitalize">{interview.level}</Badge>
                </div>
              </div>
              <div className={`px-6 py-2 rounded-2xl text-white font-black text-sm uppercase tracking-widest shadow-lg ${getRecommendationColor(summary.recommendation)}`}>
                {summary.recommendation}
              </div>
            </div>
          </CardHeader>
          <CardContent className="p-8 space-y-10">
            <div>
              <h3 className="text-xs font-bold uppercase tracking-[0.2em] text-primary mb-4">Executive Summary</h3>
              <p className="text-lg leading-relaxed text-foreground/80 whitespace-pre-wrap italic pl-4 border-l-4 border-primary/20">
                 &quot;{summary.summary || "No summary available."}&quot;
              </p>
            </div>

            <div className="grid sm:grid-cols-2 gap-10 pt-4">
              <div className="space-y-6">
                <h3 className="text-sm font-black uppercase tracking-widest text-green-600 flex items-center">
                  <CheckCircle className="mr-2 h-5 w-5" />
                  Technical Strengths
                </h3>
                <ul className="space-y-4">
                  {summary.strengths?.length > 0 ? summary.strengths.map((str: string, i: number) => (
                    <li key={i} className="flex items-start group">
                      <div className="mr-3 mt-1.5 h-2 w-2 rounded-full bg-green-500 shrink-0 shadow-[0_0_8px_rgba(34,197,94,0.5)] group-hover:scale-125 transition-transform" />
                      <span className="text-sm font-medium leading-tight">{str}</span>
                    </li>
                  )) : (
                    <p className="text-sm text-muted-foreground">None identified.</p>
                  )}
                </ul>
              </div>

              <div className="space-y-6">
                <h3 className="text-sm font-black uppercase tracking-widest text-amber-600 flex items-center">
                  <AlertCircle className="mr-2 h-5 w-5" />
                  Growth Opportunities
                </h3>
                <ul className="space-y-4">
                  {summary.weaknesses?.length > 0 ? summary.weaknesses.map((weak: string, i: number) => (
                    <li key={i} className="flex items-start group">
                      <div className="mr-3 mt-1.5 h-2 w-2 rounded-full bg-amber-500 shrink-0 shadow-[0_0_8px_rgba(245,158,11,0.5)] group-hover:scale-125 transition-transform" />
                      <span className="text-sm font-medium leading-tight">{weak}</span>
                    </li>
                  )) : (
                    <p className="text-sm text-muted-foreground">None identified.</p>
                  )}
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>

        <div className="space-y-8">
          <Card className="border-none shadow-xl rounded-3xl overflow-hidden bg-primary text-primary-foreground relative group">
            <div className="absolute top-0 right-0 p-8 opacity-10 group-hover:scale-110 transition-transform duration-500">
               <History className="h-24 w-24" />
            </div>
            <CardHeader className="pb-4">
              <CardTitle className="text-xs font-bold uppercase tracking-widest opacity-80">Final Proficiency Score</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-baseline gap-1">
                <span className="text-7xl font-black">{interview.percentage?.toFixed(0) || 0}</span>
                <span className="text-2xl font-bold opacity-60">%</span>
              </div>
              <p className="text-sm font-medium mt-4 opacity-80 bg-white/10 inline-block px-3 py-1 rounded-full">
                {interview.total_score} / {interview.max_score} Total Points
              </p>
            </CardContent>
          </Card>

          <Card className="border-none shadow-xl rounded-3xl overflow-hidden ring-1 ring-muted">
            <CardHeader className="pb-4 border-b bg-muted/20">
              <CardTitle className="text-xs font-black uppercase tracking-[0.2em] text-muted-foreground">Detailed Metadata</CardTitle>
            </CardHeader>
            <CardContent className="p-6 space-y-4">
              <div className="flex justify-between items-center py-2 border-b border-muted/50">
                <span className="text-xs font-bold text-muted-foreground uppercase">Date Conducted</span>
                <span className="text-sm font-black">
                  {new Date(interview.created_at).toLocaleDateString(undefined, { dateStyle: 'medium' })}
                </span>
              </div>
              <div className="flex justify-between items-center py-2 border-b border-muted/50">
                <span className="text-xs font-bold text-muted-foreground uppercase">Difficulty Level</span>
                <Badge variant="secondary" className="uppercase text-[10px] font-black">{interview.level}</Badge>
              </div>
              <div className="flex justify-between items-center py-2 border-b border-muted/50">
                <span className="text-xs font-bold text-muted-foreground uppercase">Total Questions</span>
                <span className="text-sm font-black">{questionCount}</span>
              </div>
              <div className="flex justify-between items-center py-2">
                <span className="text-xs font-bold text-muted-foreground uppercase">Technology</span>
                <span className="text-sm font-black text-primary">{interview.language}</span>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
