"use client";

import { useEffect, useState, useRef } from "react";
import { useParams } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Download, CheckCircle, AlertCircle, ArrowLeft, Loader2, History as HistoryIcon } from "lucide-react";
import Link from "next/link";

export default function EvaluationSummaryPage() {
  const { id } = useParams() as { id: string };
  const [loading, setLoading] = useState(true);
  
  const [interview, setInterview] = useState<any>(null);
  const [summary, setSummary] = useState<any>(null);
  const [questions, setQuestions] = useState<any[]>([]);
  const [questionCount, setQuestionCount] = useState(0);
  const [exporting, setExporting] = useState(false);
  const hasFetched = useRef(false);

  useEffect(() => {
    async function loadDataAndGenerateSummary() {
      if (hasFetched.current) return;
      hasFetched.current = true;
      
      const supabase = createClient();
      
      // 1. Fetch Interview Data
      const { data: interviewData, error: interviewError } = await supabase
        .from("interviews")
        .select("*")
        .eq("id", id)
        .single();
        
      if (interviewError || !interviewData) {
        console.error("Failed to load interview", interviewError);
        return;
      }
      setInterview(interviewData);

      // 2. Fetch Questions (for count and for PDF export)
      const { data: qData, error: qError } = await supabase
        .from("interview_questions")
        .select("*")
        .eq("interview_id", id)
        .order("order_index", { ascending: true });
        
      if (!qError && qData) {
        setQuestions(qData);
        setQuestionCount(qData.length);
      }

      // 3. Trigger / Fetch AI Summary
      try {
        const response = await fetch("/api/generate-summary", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ interviewId: id }),
        });
        const data = await response.json();
        
        if (data.success && data.summary) {
          setSummary(data.summary);
        } else {
          console.error("Summary Generation Error:", data);
        }
      } catch (err) {
        console.error("Failed to fetch summary API:", err);
      } finally {
        setLoading(false);
      }
    }

    loadDataAndGenerateSummary();
  }, [id]);

  function getRecommendationColor(rec: string | undefined) {
    if (rec === "Strong Hire" || rec === "Hire") return "bg-green-600 hover:bg-green-700";
    if (rec === "Maybe") return "bg-yellow-600 hover:bg-yellow-700";
    if (rec === "Reject") return "bg-red-600 hover:bg-red-700";
    return "bg-primary";
  }

  const handleExportPDF = async () => {
    setExporting(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF();
      const margin = 20;
      const pageWidth = doc.internal.pageSize.getWidth();
      const maxLineWidth = pageWidth - margin * 2;
      let y = 20;

      const checkPageBreak = (neededHeight = 10) => {
        if (y + neededHeight > 280) {
          doc.addPage();
          y = 20;
        }
      };

      // Header
      doc.setFont("helvetica", "bold");
      doc.setFontSize(22);
      doc.setTextColor(0, 0, 0);
      doc.text("Candidate Assessment Report", margin, y);
      y += 8;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text("Generated by VivaGen AI", margin, y);
      y += 15;

      // Candidate Info
      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.setTextColor(0, 0, 0);
      doc.text(interview.candidate_name, margin, y);
      y += 8;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(12);
      doc.setTextColor(60, 60, 60);
      doc.text(`Role: ${interview.role} (${interview.level})`, margin, y);
      y += 6;
      doc.text(`Primary Stack: ${interview.language}`, margin, y);
      y += 6;
      doc.text(`Date: ${new Date(interview.created_at).toLocaleDateString()}`, margin, y);
      y += 15;

      // Score Box Approximation
      doc.setFillColor(243, 244, 246);
      doc.roundedRect(margin, y, 70, 25, 3, 3, "F");
      
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text("Final Score", margin + 5, y + 8);
      
      doc.setFont("helvetica", "bold");
      doc.setFontSize(18);
      doc.setTextColor(17, 24, 39);
      doc.text(`${interview.percentage?.toFixed(1) || 0}%`, margin + 5, y + 15);
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text(`${interview.total_score} / ${interview.max_score} pts`, margin + 5, y + 21);
      
      y += 40;

      const printList = (title: string, items: string[]) => {
        if (!items || items.length === 0) return;
        checkPageBreak(20);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text(title, margin, y);
        y += 8;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);
        doc.setTextColor(40, 40, 40);

        items.forEach((item: string) => {
          const lines = doc.splitTextToSize(`• ${item}`, maxLineWidth - 5);
          checkPageBreak(lines.length * 6);
          doc.text(lines, margin + 2, y);
          y += lines.length * 5 + 2;
        });
        y += 10;
      };

      printList("Key Strengths", summary.strengths);
      printList("Areas for Growth", summary.weaknesses);

      // Questions
      checkPageBreak(25);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text("Interview Questions & Scores", margin, y);
      y += 10;

      questions.forEach((q: any, i: number) => {
        const qText = `${i + 1}. ${q.question}`;
        
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.setTextColor(17, 24, 39);
        
        const lines = doc.splitTextToSize(qText, maxLineWidth - 30); // leave room for score
        checkPageBreak(lines.length * 6 + 15);
        
        doc.text(lines, margin, y);
        
        // Output score on the same line as the first line of the question, right aligned
        const scoreString = `${q.score || 0}/10`;
        const scoreWidth = doc.getTextWidth(scoreString);
        doc.text(scoreString, pageWidth - margin - scoreWidth, y);
        
        y += lines.length * 5 + 2;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(`Type: ${q.type.charAt(0).toUpperCase() + q.type.slice(1)} | Difficulty: ${q.difficulty}/10`, margin, y);
        
        y += 12;
      });

      doc.save(`${interview.candidate_name.replace(/\s+/g, '_')}_Interview_Report.pdf`);

    } catch (error) {
      console.error("Export failed", error);
      alert("Failed to create PDF");
    } finally {
      setExporting(false);
    }
  };

  if (loading) {
    return (
      <div className="flex flex-col h-[calc(100vh-8rem)] items-center justify-center space-y-4">
        <Loader2 className="h-10 w-10 animate-spin text-primary" />
        <h2 className="text-xl font-semibold">Gemini AI is evaluating the interview...</h2>
        <p className="text-muted-foreground text-sm max-w-sm text-center">
          Analyzing scores and interviewer notes to generate strengths, weaknesses, and a final recommendation.
        </p>
      </div>
    );
  }

  if (!interview || !summary) {
    return (
      <div className="container mx-auto p-6 max-w-4xl text-center pt-20">
        <h2 className="text-2xl font-bold text-destructive mb-2">Evaluation Failed</h2>
        <p className="text-muted-foreground mb-6">We {"couldn't"} generate the summary at this time.</p>
        <Link href="/dashboard">
          <Button>Back to Dashboard</Button>
        </Link>
      </div>
    );
  }

  return (
    <div className="container mx-auto p-4 md:p-8 max-w-7xl space-y-10 animate-in fade-in duration-500">
      {/* Header Section */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
        <div>
          <Link href="/dashboard" className="text-xs font-bold text-muted-foreground uppercase tracking-widest flex items-center hover:text-primary mb-2 transition-colors group">
            <ArrowLeft className="mr-2 h-3 w-3 group-hover:-translate-x-1 transition-transform" />
            Back to Workspace
          </Link>
          <div className="flex items-center gap-4">
            <h1 className="text-4xl font-black tracking-tight text-foreground">
              Interview Report
            </h1>
            <div className={`px-4 py-1 rounded-full text-white font-black text-[10px] uppercase tracking-widest shadow-lg ${getRecommendationColor(summary.recommendation)}`}>
                {summary.recommendation}
            </div>
          </div>
          <p className="text-muted-foreground mt-1 font-medium text-sm">Evaluation for <span className="text-foreground font-bold">{interview.candidate_name}</span> • AI Generated Assessment</p>
        </div>
        <Button 
          size="lg" 
          className="w-full md:w-auto shadow-xl shadow-primary/20 rounded-full px-8 hover:scale-105 transition-transform" 
          onClick={handleExportPDF} 
          disabled={exporting}
        >
          {exporting ? (
            <Loader2 className="mr-2 h-5 w-5 animate-spin" />
          ) : (
            <Download className="mr-2 h-5 w-5" />
          )}
          {exporting ? "Finalizing PDF..." : "Export Assessment PDF"}
        </Button>
      </div>

      <div className="grid lg:grid-cols-12 gap-8 items-start">
        {/* Main Content Feed (LEFT - 8/12) */}
        <div className="lg:col-span-8 space-y-8">
          {/* Executive Summary Card */}
          <Card className="border-none shadow-2xl shadow-primary/5 rounded-3xl overflow-hidden ring-1 ring-primary/5">
            <CardHeader className="bg-muted/30 dark:bg-muted/10 border-b p-6">
              <h3 className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Executive Summary</h3>
            </CardHeader>
            <CardContent className="p-8">
              <p className="text-xl leading-relaxed text-foreground/80 whitespace-pre-wrap italic font-medium">
                 &quot;{summary.summary || "No summary available."}&quot;
              </p>
            </CardContent>
          </Card>

          {/* Detailed Log Card */}
          <Card className="border-none shadow-2xl shadow-primary/5 rounded-3xl overflow-hidden ring-1 ring-primary/5">
            <CardHeader className="bg-muted/30 dark:bg-muted/10 border-b p-6 flex flex-row items-center justify-between">
              <h3 className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Detailed Interview Log</h3>
              <Badge variant="outline" className="text-[10px] font-bold opacity-60 px-2">{questions.length} Questions Asked</Badge>
            </CardHeader>
            <CardContent className="p-6 space-y-4">
              {questions.map((q, i) => (
                <div key={q.id} className="p-6 rounded-2xl bg-muted/20 border border-muted/50 hover:bg-muted/40 transition-colors group">
                  <div className="flex flex-col sm:flex-row justify-between items-start gap-4 mb-3">
                    <div className="flex gap-4 items-start">
                      <span className="flex items-center justify-center w-8 h-8 rounded-xl bg-primary/10 text-primary text-xs font-black shrink-0 mt-0.5">
                        {i + 1}
                      </span>
                      <h4 className="font-bold text-lg text-foreground leading-snug group-hover:text-primary transition-colors">
                        {q.question}
                      </h4>
                    </div>
                    <div className="flex flex-row sm:flex-col items-center sm:items-end justify-between sm:justify-start w-full sm:w-auto shrink-0 pt-1 border-t sm:border-t-0 mt-2 sm:mt-0 pt-2 sm:pt-0">
                      <div className="text-xl font-black">{q.score || 0}<span className="text-xs text-muted-foreground ml-0.5 font-bold">/10</span></div>
                      <Badge variant="outline" className="text-[9px] uppercase font-black px-1.5 py-0 border-muted-foreground/20 leading-none h-4">
                        {q.type}
                      </Badge>
                    </div>
                  </div>
                  {q.notes && (
                    <div className="mt-4 pt-4 border-t border-dashed border-muted-foreground/20">
                      <p className="text-sm text-muted-foreground leading-relaxed">
                        <span className="font-extrabold text-[10px] uppercase tracking-wider text-primary/70 mr-2">Interviewer Notes:</span>
                        <span className="italic opacity-90">{q.notes}</span>
                      </p>
                    </div>
                  )}
                </div>
              ))}
            </CardContent>
          </Card>
        </div>

        {/* Action Sidebar (RIGHT - 4/12) */}
        <div className="lg:col-span-4 space-y-8 lg:sticky lg:top-24">
          {/* Score Card */}
          <Card className="border-none shadow-xl rounded-3xl overflow-hidden bg-primary text-primary-foreground relative group">
            <div className="absolute top-0 right-0 p-6 opacity-10 group-hover:scale-110 transition-transform duration-500">
               <HistoryIcon className="h-20 w-20" />
            </div>
            <CardHeader className="pb-2">
              <CardTitle className="text-xs font-bold uppercase tracking-widest opacity-80">Proficiency Score</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-baseline gap-1">
                <span className="text-7xl font-black">{interview.percentage?.toFixed(0) || 0}</span>
                <span className="text-2xl font-bold opacity-60">%</span>
              </div>
              <div className="flex items-center justify-between mt-6">
                 <p className="text-sm font-medium opacity-80 bg-white/10 px-3 py-1 rounded-full">
                   {interview.total_score} / {interview.max_score} Total Points
                 </p>
                 <Badge className="bg-white/20 hover:bg-white/30 text-white border-none text-[10px] font-black uppercase">
                   {interview.level}
                 </Badge>
              </div>
            </CardContent>
          </Card>

          {/* Analysis Cards (Strengths/Weaknesses) */}
          <Card className="border-none shadow-xl rounded-3xl overflow-hidden ring-1 ring-muted">
             <CardHeader className="p-6 border-b bg-muted/10">
                <h3 className="text-xs font-black uppercase tracking-widest text-muted-foreground">Snapshot Analysis</h3>
             </CardHeader>
             <CardContent className="p-6 space-y-8">
               {/* Strengths */}
               <div className="space-y-4">
                  <h4 className="text-[10px] font-black uppercase tracking-widest text-green-600 flex items-center">
                    <CheckCircle className="mr-2 h-4 w-4" />
                    Key Strengths
                  </h4>
                  <ul className="space-y-3">
                    {summary.strengths?.map((str: string, i: number) => (
                      <li key={i} className="flex items-start text-xs font-medium leading-normal p-2 rounded-xl bg-green-500/5 group">
                        <div className="mr-2 mt-1.5 h-1.5 w-1.5 rounded-full bg-green-500 shrink-0" />
                        {str}
                      </li>
                    ))}
                  </ul>
               </div>

               {/* Growth */}
               <div className="space-y-4">
                  <h4 className="text-[10px] font-black uppercase tracking-widest text-amber-600 flex items-center">
                    <AlertCircle className="mr-2 h-4 w-4" />
                    Growth areas
                  </h4>
                  <ul className="space-y-3">
                    {summary.weaknesses?.map((weak: string, i: number) => (
                      <li key={i} className="flex items-start text-xs font-medium leading-normal p-2 rounded-xl bg-amber-500/5 group">
                        <div className="mr-2 mt-1.5 h-1.5 w-1.5 rounded-full bg-amber-500 shrink-0" />
                        {weak}
                      </li>
                    ))}
                  </ul>
               </div>
             </CardContent>
          </Card>

          {/* Quick Info Card */}
          <Card className="border-none shadow-lg rounded-3xl overflow-hidden ring-1 ring-muted">
            <CardContent className="p-6 space-y-4">
              <div className="flex justify-between items-center text-[10px] font-bold text-muted-foreground uppercase border-b border-muted pb-3">
                <span>Details & Meta</span>
                <span className="text-primary tracking-tighter uppercase">{interview.language}</span>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1">
                   <p className="text-[9px] font-black text-muted-foreground uppercase tracking-wider">Date</p>
                   <p className="text-xs font-black">{new Date(interview.created_at).toLocaleDateString(undefined, { dateStyle: 'medium' })}</p>
                </div>
                <div className="space-y-1">
                   <p className="text-[9px] font-black text-muted-foreground uppercase tracking-wider">Interviewee</p>
                   <p className="text-xs font-black truncate">{interview.candidate_name}</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
